version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: adgen-ai-redis

    ports:
      - "6379:6379"   # expose only for local development

    command: redis-server --requirepass mypassword
    volumes:
      - redis_data:/data
    restart: always

  # redis gui
  redis-insight: 
    image: redis/redisinsight:latest
    container_name: agen-ai-redis-insight

    ports:
      - 5540:5540
    volumes:
      - redis_insight:/data
    restart: always
    depends_on:
      - redis

    

volumes:
  redis_data:
  redis_insight:


